### ISSUE TITLE
Filter host key types correctly

### ISSUE THREAD

**Issue by ghost** [oVirt/ovirt-resources-upload-action#1]
The current implementation doesn't correctly filter the host key types as the self-test indicates. The implementation should take the passed host keys and configure the client to use only those host key types that are provided.

**Comment by michalskrivanek** [comment]
is it really needed to be parsed though? we are adding the known_hosts with the supposedly valid key of a valid type, so there should always be a match

**Comment by michalskrivanek** [comment]
ok, IMHO it's the defaults coming from alpine's sshd, AFAIK you have HostKeyAlgorithms set on sshd side to something that's not generated by ssh-keygen on ubuntu. 
I think it's not  useful to restrict client to certain host key algorithms since they are part of provided known_hosts

**Comment by ghost** [comment]
The client / action implementation should be able to handle not having all host key types provided. That's why I was trying to add filtering, but it doesn't seem to work.

**Comment by michalskrivanek** [comment]
also, there's a further problem with find in alpine -
find: unrecognized: -printf

**Comment by michalskrivanek** [comment]
> The client / action implementation should be able to handle not having all host key types provided. That's why I was trying to add filtering, but it doesn't seem to work.

sure, but why does it matter really? either the provided host_key is not of the type that server accepts -> auth fails. or it does, and then it should succeed if the key is correct.

**Comment by michalskrivanek** [comment]
> also, there's a further problem with find in alpine - find: unrecognized: -printf

note that printf works on the actual server that this action is supposed to works with.

**Comment by ghost** [comment]
As you see in the test, unfortunately it doesn't continue. The whole process fails if it can't query for the approval.

**Comment by ghost** [comment]
https://github.com/oVirt/ovirt-resources-upload-action/runs/4925371283?check_suite_focus=true

**Comment by michalskrivanek** [comment]
I don't think it's the key, I think alpine has a crappy sshd. I think it's worth switching the image to something else, el8stream or rhel8 UBI. But otherwise not really worth spending time. This action is supposed to work with one rhel-based server and it does works correctly with it.
